name: CI – Build & Test

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: dotnet restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore


  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Test
      run: dotnet test  --configuration Release --verbosity normal p:CollectCoverage=true p:CoverletOutputFormat=opencover 

    - name: Report code coverage
      uses: codecov/codecov-action@v2