name: CI - Build & Test

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Test
        run: dotnet test --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./TestResults/ /p:MergeWith=./TestResults/coverage.opencover.xml /p:Exclude="[xunit.*]*,[FluentAssertions.*]*,[NUnit.*]*,[Moq.*]*,[System.*]*,[Microsoft.*]*,[netstandard.*]*,[netcoreapp.*]*,[net5.0.*]*,[net6.0.*]*,[net7.0.*]*,[net8.0.*]*" --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        

      - name: Report code coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./TestResults/coverage.opencover.xml
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
